export const appEl1 = `<div class="CARDS">
<div class="card"><img class="card-img" src="static/img/card/туз пики.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/король пики.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/дама пики.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/валет пики.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/10 пики.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/9 пики.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/8 пики.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/7 пики.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/6 пики.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/туз черви.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/король черви.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/дама черви.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/валет черви.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/10 черви.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/9 черви.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/8 черви.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/7 черви.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/6 черви.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/туз бубны.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/король бубны.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/дама бубны.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/валет бубны.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/10 бубны.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/9 бубны.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/8 бубны.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/7 бубны.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/6 бубны.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/туз крести.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/король крести.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/дама крести.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/валет крести.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/10 крести.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/9 крести.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/8 крести.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/7 крести.svg" alt=""></div>
<div class="card"><img class="card-img" src="static/img/card/6 крести.svg" alt=""></div>
</div>
`
